# Generated by Django 2.2.10 on 2020-06-21 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('article', tinymce.models.HTMLField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeleCallDoctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('practicing_year', models.CharField(blank=True, max_length=20, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('hospital', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_id', models.CharField(blank=True, max_length=200, null=True)),
                ('available_from', models.CharField(blank=True, max_length=200, null=True)),
                ('available_to', models.CharField(blank=True, max_length=200, null=True)),
                ('direct_contact', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Paramedics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('qualifications', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('available_from', models.CharField(max_length=200)),
                ('available_to', models.CharField(max_length=200)),
                ('achievements', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('address', models.TextField()),
                ('designation', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('license_no', models.CharField(max_length=100, unique=True)),
                ('collection', models.BooleanField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('education', models.TextField()),
                ('practicing_year', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='doctors/')),
                ('gender', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('lat', models.CharField(max_length=100)),
                ('lon', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('videoconferencing', models.BooleanField(default=False)),
                ('telecalling', models.BooleanField(default=False)),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('signuptime', models.DateTimeField(auto_now=True)),
                ('direct_contact', models.BooleanField(default=False)),
                ('designation', models.CharField(max_length=300)),
                ('hospital', models.CharField(max_length=300)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.City')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.State')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Type')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('query', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.State'),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.City'),
        ),
    ]
