# Generated by Django 2.2.10 on 2020-04-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200424_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecalldoctors',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
