# Generated by Django 2.2.10 on 2020-06-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200621_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_category',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
