# Generated by Django 2.2.10 on 2020-04-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_telecalldoctors_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecalldoctors',
            name='hospital',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
