# Generated by Django 2.2.10 on 2020-06-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_type_type_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramedics',
            name='collection',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
