# Generated by Django 2.2.10 on 2020-04-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_telecalldoctors_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecalldoctors',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
