# Generated by Django 2.2.10 on 2020-04-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_telecalldoctors_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
