# Generated by Django 2.2.10 on 2020-04-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_type_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecalldoctors',
            name='direct_contact',
            field=models.BooleanField(default=False),
        ),
    ]
