# Generated by Django 2.2.10 on 2020-06-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200628_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
    ]
