# Generated by Django 2.2.10 on 2020-04-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200426_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecalldoctors',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
