# Generated by Django 2.2.10 on 2020-04-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_telecalldoctors_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecalldoctors',
            name='availabel_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='telecalldoctors',
            name='availabel_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='telecalldoctors',
            name='registration_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
