# Generated by Django 2.2.10 on 2020-06-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200628_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='Being Social Thankfully the Brain'),
            preserve_default=False,
        ),
    ]
