# Generated by Django 2.2.10 on 2020-04-30 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200429_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('collection', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DrugHouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('license_no', models.CharField(max_length=100, unique=True)),
                ('about', models.TextField()),
                ('phone', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paramedics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('qualifications', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('available_from', models.CharField(max_length=200)),
                ('available_to', models.CharField(max_length=200)),
                ('achievments', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='telecalldoctors',
            old_name='availabel_from',
            new_name='available_from',
        ),
        migrations.RenameField(
            model_name='telecalldoctors',
            old_name='availabel_to',
            new_name='available_to',
        ),
        migrations.CreateModel(
            name='ClinicalPsychiatry',
            fields=[
                ('paramedics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Paramedics')),
            ],
            bases=('app.paramedics',),
        ),
        migrations.CreateModel(
            name='HealthFitnessAdvisor',
            fields=[
                ('paramedics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Paramedics')),
                ('designation', models.CharField(max_length=200)),
            ],
            bases=('app.paramedics',),
        ),
        migrations.CreateModel(
            name='Physiotherapist',
            fields=[
                ('paramedics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Paramedics')),
                ('designation', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
            ],
            bases=('app.paramedics',),
        ),
        migrations.CreateModel(
            name='YogaGuru',
            fields=[
                ('paramedics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Paramedics')),
                ('organization', models.CharField(max_length=200)),
            ],
            bases=('app.paramedics',),
        ),
    ]
