# Generated by Django 2.2.10 on 2020-04-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200430_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalpsychiatry',
            name='designation',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalpsychiatry',
            name='organization',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
