# Generated by Django 2.2.10 on 2020-04-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200430_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paramedics',
            old_name='achievments',
            new_name='achievements',
        ),
    ]
