# Generated by Django 2.2.10 on 2020-07-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200708_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
