# Generated by Django 2.2.10 on 2020-07-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20200728_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='practice_id',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
