# Generated by Django 2.2.10 on 2020-07-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_doctor_practice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
