# Generated by Django 2.2.10 on 2020-07-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_prescription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
