# Generated by Django 2.2.10 on 2020-07-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200731_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
