# Generated by Django 2.2.10 on 2020-07-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20200801_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='remarks',
        ),
        migrations.AddField(
            model_name='medicine',
            name='remarks',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
