# Generated by Django 2.2.10 on 2020-07-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_prescription_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='datetime',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
