# Generated by Django 3.0.5 on 2020-08-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20200801_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='datetime',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
