# Generated by Django 2.2.5 on 2020-08-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_feedback_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='status',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='doctor_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='patient_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
