# Generated by Django 2.2.5 on 2020-08-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20200808_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status_patient',
            field=models.BooleanField(default=False),
        ),
    ]
