# Generated by Django 2.2.5 on 2020-08-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20200808_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='signature_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
