# Generated by Django 2.2.10 on 2020-09-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_indexcms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='cms/')),
                ('name', models.CharField(max_length=100)),
                ('alt', models.CharField(max_length=100)),
            ],
        ),
    ]
