# Generated by Django 2.2.10 on 2020-06-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200621_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramedics',
            name='qualifications',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
