# Generated by Django 2.2.10 on 2020-06-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200628_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.ImageField(default='default.png', upload_to='types'),
        ),
    ]
