# Generated by Django 2.2.10 on 2020-06-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.ImageField(default='types/default.png', upload_to='types/'),
        ),
    ]
