# Generated by Django 2.2.10 on 2020-06-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamedicBookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('query', models.TextField()),
                ('type', models.CharField(max_length=3)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
                ('paramedic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Paramedics')),
            ],
        ),
    ]
