# Generated by Django 2.2.10 on 2020-06-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_paramedicbookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paramedicbookings',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
