# Generated by Django 2.2.10 on 2020-06-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200628_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='status',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='paramedicbookings',
            name='status',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
