# Generated by Django 2.2.10 on 2020-07-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200708_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
