# Generated by Django 2.2.10 on 2020-07-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_customer_razor_pay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
