# Generated by Django 2.2.10 on 2020-07-27 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_appointments_razor_pay_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.BooleanField(max_length=300)),
                ('morning', models.BooleanField(max_length=10)),
                ('lunch', models.BooleanField(max_length=10)),
                ('evening', models.BooleanField(max_length=10)),
                ('dinner', models.BooleanField(max_length=10)),
                ('afterFood', models.BooleanField(max_length=300)),
                ('period', models.BooleanField(max_length=300)),
                ('quantity', models.BooleanField(max_length=300)),
                ('remarks', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Appointments')),
            ],
        ),
    ]
