# Generated by Django 2.2.10 on 2020-07-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200728_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(max_length=300),
        ),
    ]
