# Generated by Django 2.2.10 on 2020-07-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_appointments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='count',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
