# Generated by Django 2.2.10 on 2020-07-31 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20200731_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='afterFood',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='date',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='evening',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='morning',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='period',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity',
        ),
        migrations.AddField(
            model_name='prescription',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=300)),
                ('morning', models.BooleanField(max_length=10)),
                ('lunch', models.BooleanField(max_length=10)),
                ('evening', models.BooleanField(max_length=10)),
                ('dinner', models.BooleanField(max_length=10)),
                ('afterFood', models.BooleanField(max_length=300)),
                ('period', models.CharField(max_length=300)),
                ('quantity', models.CharField(max_length=300)),
                ('prescription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Prescription')),
            ],
        ),
    ]
