# Generated by Django 2.2.10 on 2020-07-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200801_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='meeting_close',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
