# Generated by Django 2.2.10 on 2020-07-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_prescription_meeting_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='slug',
            field=models.SlugField(default='asasasdasd'),
            preserve_default=False,
        ),
    ]
