# Generated by Django 2.2.10 on 2020-08-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20200802_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_rating', models.CharField(blank=True, max_length=1, null=True)),
                ('doctor_comments', models.CharField(blank=True, max_length=1, null=True)),
                ('patient_rating', models.CharField(blank=True, max_length=1, null=True)),
                ('patient_comments', models.CharField(blank=True, max_length=1, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Prescription')),
            ],
        ),
    ]
