# Generated by Django 2.2.10 on 2020-08-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20200802_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fees',
            field=models.CharField(default='250', max_length=100),
            preserve_default=False,
        ),
    ]
