# Generated by Django 2.2.10 on 2020-08-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_doctor_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='special_day',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='special_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='special_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
