# Generated by Django 2.2.10 on 2020-08-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20200806_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.FileField(default='types/default.png', upload_to='types/'),
        ),
    ]
