# Generated by Django 2.2.10 on 2020-08-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20200809_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_from2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_to2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
