# Generated by Django 2.2.10 on 2020-08-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20200813_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='razor_pay_order_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='signature_id',
        ),
        migrations.AddField(
            model_name='appointments',
            name='payment_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointments',
            name='signature_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
