# Generated by Django 4.2.2 on 2023-07-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='time',
        ),
    ]
