# Generated by Django 4.2.2 on 2023-07-24 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_remove_appointments_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 8, 54, 32, 567661, tzinfo=datetime.timezone.utc)),
        ),
    ]
