# Generated by Django 4.2.2 on 2023-07-24 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_appointments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 9, 9, 10, 208799, tzinfo=datetime.timezone.utc)),
        ),
    ]
