# Generated by Django 4.2.2 on 2023-07-25 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_appointments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 9, 56, 2, 332107, tzinfo=datetime.timezone.utc)),
        ),
    ]
